# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='tshirtSize',
            field=models.CharField(choices=[('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4),
        ),
    ]
