# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0002_auto_20170323_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=30)),
                ('phone', localflavor.us.models.PhoneNumberField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('street', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='Fairview', max_length=90)),
                ('state', localflavor.us.models.USStateField(default='TX', max_length=2)),
                ('zipCode', localflavor.us.models.USZipCodeField(default='75069', max_length=10)),
                ('meal1', models.BooleanField(default=False)),
                ('meal2', models.BooleanField(default=False)),
                ('hostHome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnow.HostHome')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=30)),
                ('phone', localflavor.us.models.PhoneNumberField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('street', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='Fairview', max_length=90)),
                ('state', localflavor.us.models.USStateField(default='TX', max_length=2)),
                ('zipCode', localflavor.us.models.USZipCodeField(default='75069', max_length=10)),
                ('carCapacity', models.IntegerField()),
                ('bgCheck', models.BooleanField(default=False)),
                ('driveSlot1', models.BooleanField(default=False)),
                ('driveSlot2', models.BooleanField(default=False)),
                ('driveSlot3', models.BooleanField(default=False)),
                ('driveSlot4', models.BooleanField(default=False)),
                ('driveSlot5', models.BooleanField(default=False)),
                ('driveSlot6', models.BooleanField(default=False)),
                ('driveSlot7', models.BooleanField(default=False)),
                ('hostHome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnow.HostHome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
