# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-07 03:23
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0003_cook_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parentPhone',
            field=localflavor.us.models.PhoneNumberField(default='', max_length=20),
        ),
    ]
