# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0004_student_parentphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cook',
            name='tshirtSize',
            field=models.CharField(choices=[('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4),
        ),
        migrations.AddField(
            model_name='driver',
            name='tshirtSize',
            field=models.CharField(choices=[('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4),
        ),
        migrations.AddField(
            model_name='hosthome',
            name='tshirtSize',
            field=models.CharField(choices=[('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4),
        ),
    ]
