# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0007_auto_20171122_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=30)),
                ('lastName', models.CharField(default='', max_length=30)),
                ('phone', localflavor.us.models.PhoneNumberField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('street', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='Fairview', max_length=90)),
                ('state', localflavor.us.models.USStateField(default='TX', max_length=2)),
                ('zipCode', localflavor.us.models.USZipCodeField(default='75069', max_length=10)),
                ('bgCheck', models.BooleanField(default=False)),
                ('tshirtSize', models.CharField(choices=[('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=16)),
                ('hostHome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnow.HostHome')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
