# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-23 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0008_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='hostHome',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='meal1',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='meal2',
        ),
        migrations.AddField(
            model_name='cook',
            name='meal1HostHome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal1', to='dnow.HostHome'),
        ),
        migrations.AddField(
            model_name='cook',
            name='meal2HostHome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal2', to='dnow.HostHome'),
        ),
    ]
