# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-25 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0009_auto_20171122_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='meal1HostHome',
        ),
        migrations.RemoveField(
            model_name='cook',
            name='meal2HostHome',
        ),
        migrations.AddField(
            model_name='cook',
            name='mealHostHomes',
            field=models.ManyToManyField(blank=True, null=True, to='dnow.HostHome'),
        ),
    ]
