# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0012_auto_20171124_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='mealHostHomes',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driveSlot1',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driveSlot2',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driveSlot3',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driveSlot4',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driveSlot5',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driveSlot6',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='driveSlot7',
        ),
        migrations.RemoveField(
            model_name='hosthome',
            name='cook1LastName',
        ),
        migrations.RemoveField(
            model_name='hosthome',
            name='cook2LastName',
        ),
    ]
