# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0013_auto_20171203_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='hostHome',
        ),
    ]
