# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0015_auto_20171203_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriveSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnow.Driver')),
                ('hostHome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnow.HostHome')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=40)),
                ('cook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnow.Cook')),
                ('hostHome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnow.HostHome')),
            ],
        ),
    ]
