# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0017_auto_20171205_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveslot',
            name='time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
