# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-16 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0018_auto_20171205_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='isDriving',
            field=models.BooleanField(default=False),
        ),
    ]
