# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0019_leader_isdriving'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parentEmail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='cook',
            name='tshirtSize',
            field=models.CharField(choices=[('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='-', max_length=4),
        ),
    ]
