# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-03 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0021_leader_churchstaff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='friendName',
            field=models.CharField(default='', max_length=80),
        ),
    ]
