# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-04 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0022_auto_20180102_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosthome',
            name='allergy',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='leader',
            name='allergy',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='student',
            name='allergy',
            field=models.CharField(default='', max_length=80),
        ),
    ]
