# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-09 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0025_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='church',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthDate',
        ),
    ]
