# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0032_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('includeData', multiselectfield.db.fields.MultiSelectField(choices=[('hostHomeBasics', 'Host Home Basics'), ('churchStaff', 'Church Staff'), ('cooks', 'Cooks'), ('driverData', 'Driver Data'), ('leaders', 'Leaders'), ('students', 'Students'), ('tshirts', 'T-Shirts')], max_length=68)),
            ],
        ),
        migrations.CreateModel(
            name='EmailToGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toGroups', multiselectfield.db.fields.MultiSelectField(choices=[('hostHomes', 'Host Homes'), ('parents', 'Parents'), ('drivers', 'Drivers'), ('leaders', 'Leaders'), ('students', 'Students')], max_length=42)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='includeData',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='toGroups',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='includeData',
            field=models.ManyToManyField(default=0, to='dnow.EmailData'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='toGroups',
            field=models.ManyToManyField(default=0, to='dnow.EmailToGroups'),
        ),
    ]
