# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 03:00
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0033_auto_20190101_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='includeData',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='includeData',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hostHomeBasics', 'Host Home Basics'), ('churchStaff', 'Church Staff'), ('cooks', 'Cooks'), ('driverData', 'Driver Data'), ('leaders', 'Leaders'), ('students', 'Students'), ('tshirts', 'T-Shirts')], default=None, max_length=68),
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='toGroups',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='toGroups',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hostHomes', 'Host Homes'), ('parents', 'Parents'), ('drivers', 'Drivers'), ('leaders', 'Leaders'), ('students', 'Students')], default=None, max_length=42),
        ),
        migrations.DeleteModel(
            name='EmailData',
        ),
        migrations.DeleteModel(
            name='EmailToGroups',
        ),
    ]
