# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0035_auto_20190105_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='googleDriveEmail',
            new_name='churchEmailAddress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='church',
            new_name='churchName',
        ),
        migrations.AddField(
            model_name='profile',
            name='churchEmailPassword',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
