# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0036_auto_20190106_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveslot',
            name='time',
            field=models.CharField(default='', max_length=40),
        ),
    ]
