# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 04:36
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0038_auto_20190107_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='toGroups',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hostHomes', 'Host Homes'), ('parents', 'Parents'), ('drivers', 'Drivers'), ('leaders', 'Leaders')], default=None, max_length=33),
        ),
    ]
