# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0040_emailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='toGroups',
            field=models.CharField(choices=[('hostHomes', 'Host Homes'), ('parents', 'Parents'), ('drivers', 'Drivers'), ('leaders', 'Leaders')], default=None, max_length=50),
        ),
    ]
