# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-13 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0041_auto_20190112_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='tshirtSize',
            field=models.CharField(choices=[('XS', 'XS'), ('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='-', max_length=4),
        ),
        migrations.AlterField(
            model_name='driver',
            name='tshirtSize',
            field=models.CharField(choices=[('XS', 'XS'), ('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=4),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='toGroups',
            field=models.CharField(choices=[('hostHomes', 'Host Homes'), ('parents', 'Parents'), ('drivers', 'Drivers'), ('leaders', 'Leaders'), ('cooks', 'Cooks')], default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='hosthome',
            name='tshirtSize',
            field=models.CharField(choices=[('XS', 'XS'), ('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=16),
        ),
        migrations.AlterField(
            model_name='leader',
            name='tshirtSize',
            field=models.CharField(choices=[('XS', 'XS'), ('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=16),
        ),
        migrations.AlterField(
            model_name='student',
            name='tshirtSize',
            field=models.CharField(choices=[('XS', 'XS'), ('Small', 'S'), ('Med', 'M'), ('Large', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=16),
        ),
    ]
