# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-14 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0042_auto_20190113_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='toGroups',
            field=models.CharField(choices=[('hostHomes', 'Host Homes'), ('parents', 'Parents'), ('leaders', 'Leaders'), ('drivers', 'Drivers (Include sections is ignored)'), ('cooks', 'Cooks (Include sections is ignored)')], default=None, max_length=50),
        ),
    ]
