# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0044_auto_20190113_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='driveTimeColumns',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='mealColumns',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
