# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0045_auto_20190115_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scheduleFileName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='includeData',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hostHomeBasics', 'Host Home Basics'), ('churchStaff', 'Church Staff'), ('cooks', 'Cooks'), ('driverData', 'Driver Data'), ('leaders', 'Leaders'), ('students', 'Students'), ('tshirts', 'T-Shirts'), ('schedule', 'Schedule'), ('waiver', 'Waiver')], default=None, max_length=84),
        ),
    ]
