# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 03:37
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dnow', '0046_auto_20190115_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='includeData',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('hostHomeBasics', 'Host Home Basics'), ('churchStaff', 'Church Staff'), ('cooks', 'Cooks'), ('driverData', 'Driver Data'), ('leaders', 'Leaders'), ('students', 'Students'), ('tshirts', 'T-Shirts'), ('schedule', 'Schedule')], default=None, max_length=77),
        ),
    ]
